name: Run tests

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run regression test
      run: docker run --rm -v `realpath .`:/tmp sgherbst/opencv-gcc:0.1 bash /tmp/test.sh
